project:
  type: book
  output-dir: docs


book:
  title: "Neural Networks: Zero to Hero"
  subtitle: "Book Version of Andrej Karparthy's [Neural Networks: Zero to Hero](https://www.youtube.com/watch?v=VMj-3S1tku0&list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ)"
  author: "Vinay Varma K"
  navbar: 
    left: 
      - text: "Vinay's Blog"
        href: https://vinayvarmak.com/
  sidebar:
    search: true
  twitter-card: true
  repo-url: https://github.com/NeuralNetsZeroToHero/NeuralNetsZeroToHero.github.io/
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin,facebook]
  date: "last-modified"
  date-format: long
  chapters:
    - index.qmd
    - 1_intro.ipynb

bibliography: references.bib


format:
  html:
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

comments:
  hypothesis: true


