project:
  type: book
  output-dir: docs


book:
  title: "ZeroToHero"
  author: "Vinay Varma K"
  search: true
  twitter-card: true
  repo-url: https://github.com/NeuralNetsZeroToHero/NeuralNetsZeroToHero.github.io/
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin,facebook]
  date: "6/14/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


margin-header: |
 [Vinay's Blog](https://quarto.org/docs/websites/website-tools.html#headers-footers)


format:
  html:
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



